services:

  exercise_doc:
    image: joseluisq/static-web-server:2
    container_name: exercise-doc
    restart: unless-stopped
    profiles: ["public"]
    ports:
      - 9055:80
    volumes:
      - ${PROJECT_ROOT}/build/web:/public
    environment:
      - SERVER_PORT=80
      - SERVER_ROOT=/public
      - PUID=1000
      - PGID=1000
